[tools]
argon = "argon-rbx/argon@2.0.0-pre3"
stylua = "JohnnyMorganz/stylua@0.20.0"
selene = "Kampfkarren/selene@0.26.1"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.1"
