name: Release

on:
  push:
    tags: ["*"]

jobs:
  draft-release:
    name: Draft Release
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
      release_id: ${{ steps.create-release.outputs.id }}

    steps:
      - uses: actions/checkout@v4

      - name: Read Changelog
        id: read-changes
        uses: mindsers/changelog-reader-action@v2
        with:
          version: Unreleased

      - name: Create Release
        id: create-release
        uses: shogo82148/actions-create-release@v1
        with:
          release_name: ${{ github.ref_name }}
          body: ${{ steps.read-changes.outputs.changes }}
          prerelease: ${{ contains(github.ref_name, 'pre') }}
          draft: true

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: draft-release

    steps:
      - uses: actions/checkout@v4

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2

      - name: Build
        run: argon build -vvvv

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Argon.rbxm
          path: Argon.rbxm

      - name: Upload to Release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ needs.draft-release.outputs.upload_url }}
          asset_name: Argon.rbxm
          asset_path: Argon.rbxm

  bump:
    name: Bump Version
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Update Changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v2
        with:
          tag: ${{ github.ref_name }}

      - name: Bump Wally version
        uses: DervexDev/file-version-bumper@v1
        with:
          path: ./wally.toml

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          message: Bump Version to ${{ github.ref_name }}
          default_author: github_actions

  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: [bump, draft-release]

    steps:
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.draft-release.outputs.release_id }}
